# Generated by Django 4.2.6 on 2024-02-13 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0067_task_priority"),
        ("engine", "0078_alter_cloudstorage_credentials"),
    ]

    operations = []
