# Generated by Django 4.2.6 on 2024-02-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0079_merge_20240213_0800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationguide",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
