# Generated by Django 4.2.6 on 2024-09-02 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0080_alter_annotationguide_id"),
        ("engine", "0082_alter_labeledimage_job_and_more"),
    ]

    operations = []
