# Generated by Django 4.2.6 on 2024-09-02 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics_report", "0002_alter_analyticsreport_id"),
        ("analytics_report", "0002_fix_annotation_speed"),
    ]

    operations = []
