# Generated by Django 3.2.15 on 2023-11-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebotics', '0008_alter_galleryimportprogress_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImportProgress',
        ),
    ]
