# Generated by Django 3.2.15 on 2023-11-06 07:16

from django.db import migrations
import logging


logger = logging.getLogger()


def remove_pentest_projects(apps, schema_migration):
    try:
        User = apps.get_model('auth.User')
        Project = apps.get_model('engine.Project')
        user = User.objects.get(username='pentest_user')
        Project.objects.filter(owner=user).delete()
    except Exception as e:
        logger.warning(f'Failed to remove pentest projects: {e}')


class Migration(migrations.Migration):

    dependencies = [
        ('rebotics', '0009_delete_galleryimportprogress'),
    ]

    operations = [
        migrations.RunPython(remove_pentest_projects, migrations.RunPython.noop)
    ]
