# Generated by Django 4.2.6 on 2024-02-13 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_auto_20220620_0814"),
        ("organizations", "0002_invitation_sent_date"),
    ]

    operations = []
