# Generated by Django 4.2.6 on 2024-02-13 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0003_auto_20221028_0909"),
        ("webhooks", "0004_alter_webhook_target_url"),
    ]

    operations = []
