version: '3.3'

services:
  cvat_db:
    container_name: reb_cvat_db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - reb_cvat_db:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  cvat_redis:
    container_name: reb_cvat_redis
    image: redis:7.2.3-alpine
    restart: unless-stopped
    ports:
      - "6385:6379"

  cvat_opa:
    container_name: reb_cvat_opa
    image: retechlabs/rebotics-cvat-opa:${VERSION:-latest}
    restart: unless-stopped
    ports:
      - "8181:8181"

  cvat_minio:
    container_name: reb_cvat_minio
    image: minio/minio:latest
    restart: unless-stopped
    entrypoint: sh
    command: -c 'mkdir -p /data/demo-bucket && minio server /data --address 0.0.0.0:9000'
    environment:
      MINIO_ROOT_USER: 'minio_admin'
      MINIO_ROOT_PASSWORD: 'minio_admin'
    volumes:
      - ../.s3:/data
    ports:
      - "9006:9000"

volumes:
  reb_cvat_db:

networks:
  reboticsadmin_default:
    external: true
  rebotics-management-django_default:
    external: true
