# Generated by Django 4.2.6 on 2024-09-02 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "quality_control",
            "0002_alter_annotationconflict_id_alter_annotationid_id_and_more",
        ),
        ("quality_control", "0003_qualityreport_assignee_last_updated_and_more"),
    ]

    operations = []
